# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claims',
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('true', 'True'), ('inconclusive', 'Inconclusive'), ('false', 'False')], max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='claims.Claim')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evidences',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/claims/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'links',
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='file',
            field=models.ManyToManyField(to='claims.File'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='link',
            field=models.ManyToManyField(to='claims.Link'),
        ),
        migrations.AddField(
            model_name='claim',
            name='file',
            field=models.ManyToManyField(to='claims.File'),
        ),
        migrations.AddField(
            model_name='claim',
            name='link',
            field=models.ManyToManyField(to='claims.Link'),
        ),
    ]
