# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='file',
            field=models.ManyToManyField(db_table='claim_files', to='claims.File'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='link',
            field=models.ManyToManyField(db_table='claim_links', to='claims.Link'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.ManyToManyField(db_table='evidence_files', to='claims.File'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='link',
            field=models.ManyToManyField(db_table='evidence_links', to='claims.Link'),
        ),
    ]
