# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/claims/%Y/%m/%d/')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.Claim')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/evidence/%Y/%m/%d/')),
            ],
        ),
        migrations.RenameField(
            model_name='claimlink',
            old_name='text',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='evidencelink',
            old_name='text',
            new_name='link',
        ),
        migrations.AlterField(
            model_name='evidence',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='claims.Claim'),
        ),
        migrations.AddField(
            model_name='evidencefile',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.Evidence'),
        ),
    ]
