# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_renamed_relation_tables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='file',
            new_name='files',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='link',
            new_name='links',
        ),
        migrations.RenameField(
            model_name='evidence',
            old_name='file',
            new_name='files',
        ),
        migrations.RenameField(
            model_name='evidence',
            old_name='link',
            new_name='links',
        ),
    ]
