# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_filefields_and_renamed_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimfile',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='claims.Claim'),
        ),
        migrations.AlterField(
            model_name='claimlink',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='claims.Claim'),
        ),
        migrations.AlterField(
            model_name='evidencefile',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='claims.Evidence'),
        ),
        migrations.AlterField(
            model_name='evidencelink',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='claims.Evidence'),
        ),
    ]
