# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_auto_20180303_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='evidence',
            old_name='created_by',
            new_name='user',
        ),
    ]
