# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_renamed_user_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='evidence',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
