# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_auto_20180303_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/%Y/%m/%d/'),
        ),
    ]
