# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_changed_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='text',
            field=models.TextField(),
        ),
    ]
