# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_auto_20180304_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=400, upload_to='files/%Y/%m/%d/'),
        ),
    ]
