# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0008_change_length_of_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
