# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-18 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0010_renamed_status_to_conclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.TextField(),
        ),
    ]
