# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-19 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0011_change_filefield_to_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='image',
            field=models.ImageField(default=None, height_field='image_height', upload_to='claims/images/%Y/%m/%d', width_field='image_width'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
