# Generated by Django 2.1 on 2018-08-17 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0013_file_size_and_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='link',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
