#!/bin/sh

test -z $1 && echo 'usage: ./getuser <userid>' && exit 1
test -z $token && echo '$token must be defined' && exit 2

curl http://localhost:4000/api/v1/graphql \
  -XPOST \
  -i \
  -H 'Content-type: application/json' \
  -H 'Authorization: '$token \
  -d '{"query": "query { getUserById(id: '$1') {id, name, email, username} }"}'
