#!/bin/sh

test -z $1 && echo 'usage: ./signup <username> <email> <name> <pass>' && exit 1

curl http://localhost:4000/api/v1/auth/register \
    -XPOST \
    -i \
    -H 'Content-type: application/json'
    -d '{"username": "'$1'", "email": "'$2'", "name": "'$3'", "password": "'$4'"}'
