# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_removed_redundant_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, height_field='avatar_height', null=True, upload_to='users/images/%Y/%m/%d', width_field='avatar_width'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
