# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-18 14:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_forgot_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 19, 14, 24, 31, 637154, tzinfo=utc)),
        ),
    ]
