# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-19 19:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_file_size_and_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 19, 12, 55, 673466, tzinfo=utc)),
        ),
    ]
