# Generated by Django 2.1 on 2018-08-16 12:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_on_delete_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 17, 12, 11, 35, 60960, tzinfo=utc)),
        ),
    ]
