# Generated by Django 2.1 on 2018-08-17 19:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_related_name_of_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 18, 19, 54, 27, 356358, tzinfo=utc)),
        ),
    ]
