version: '3'
services:
  db:
    image: 'mysql:5.7'    
    ports:      
      - "3307:3306"
    environment:         
        MYSQL_ROOT_PASSWORD: factlist
        MYSQL_DATABASE: factlist-api
        MYSQL_USER: factlist
        MYSQL_PASSWORD: factlist
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - /app/node_modules
      - ./:/app
    environment: 
          DB_USER: factlist
          DB_PASSWORD: factlist
          DB_NAME: factlist-api
          DB_HOST: db         
          PORT: 4000
          TWITTER_CONSUMER_SECRET: TWITTER_CONSUMER_SECRET
          TWITTER_CONSUMER_KEY: TWITTER_CONSUMER_KEY
          TWITTER_CALLBACK_URL: TWITTER_CALLBACK_URL
          MAILGUN_API_KEY: MAILGUN_API_KEY
          EMBEDLY_API_KEY: EMBEDLY_API_KEY            
    ports:
      - '4000:4000'    


