# Generated by Django 2.1 on 2018-08-16 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perspective', '0001_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='perspective.Issue'),
        ),
    ]
